name: Build and Publish

on:
  push:
    tags:
      - v*
    branches:
      - main

permissions:
  actions: write
  contents: read
  packages: write

jobs:
  test:
    name: 🪢 Test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
      - name: ⎔ Setup node
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: 'https://npm.pkg.github.com'
          cache: 'yarn'
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - run: yarn test:ci


  build:
    name: 🚧 Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: ⎔ Setup node
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: 'https://npm.pkg.github.com'
          cache: 'yarn'
      - name: ⛓ Install dependencies
        run: yarn --frozen-lockfile
      - name: 📦 Build
        run: yarn build
      - uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: ./dist

      - name: 💾 Cache
        id: cache-build
        uses: actions/cache@v3
        with:
          path: ./dist
          key: ${{ github.sha }}

  publish:
    name: 🚀 Publish
    runs-on: ubuntu-latest
    needs: [test, build]

    permissions:
      contents: write
      packages: write

    steps:
      - uses: actions/checkout@v4
      - name: ⎔ Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'
          registry-url: https://npm.pkg.github.com/

      # - name: Check package version
      #   uses: majortom327/auto-version@v0.0.3
      #   with:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/cache@v3
        id: cache-build
        with:
          path: ./dist
          key: ${{ github.sha }}


      - name: 🚀 Publish to NPM
        if: startsWith(github.ref, 'refs/tags/')
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          dry-run: false
